version: "3.7"

services:
  db:
    container_name: ${CONTAINER_NAME_PREFIX}db
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db

  pma:
    container_name: ${CONTAINER_NAME_PREFIX}pma
    image: phpmyadmin
    ports:
      - ${PMA_PORT:-8080}:80
    networks:
      - db
    depends_on:
      - db

  app:
    container_name: ${CONTAINER_NAME_PREFIX}app
    image: ${CONTAINER_REPOSITORY}/app
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini:ro
      - ${ENV_FILE_PATH}:/var/www/.env:ro
      - ${STORAGE_PATH}:/var/www/storage
    networks:
      - app
      - db
    depends_on:
      - db
    restart: on-failure

  webserver:
    container_name: ${CONTAINER_NAME_PREFIX}webserver
    image: ${CONTAINER_REPOSITORY}/webserver
    restart: unless-stopped
    ports:
      - ${WEBSERVER_PORT:-80}:80
    volumes:
      - ./webserver/conf.d/:/etc/nginx/conf.d/
      - ${STORAGE_PATH}:/var/www/storage
    networks:
      - app
    depends_on:
      - app

  queue:
    container_name: ${CONTAINER_NAME_PREFIX}queue
    image: ${CONTAINER_REPOSITORY}/queue
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini:ro
      - ${ENV_FILE_PATH}:/var/www/.env:ro
      - ${STORAGE_PATH}:/var/www/storage
    networks:
      - db
    depends_on:
      - db

  schedule:
    container_name: ${CONTAINER_NAME_PREFIX}schedule
    image: ${CONTAINER_REPOSITORY}/schedule
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini:ro
      - ${ENV_FILE_PATH}:/var/www/.env:ro
      - ${STORAGE_PATH}:/var/www/storage
    networks:
      - db
    depends_on:
      - db

networks:
  app:
  db:

volumes:
  db_data:
