version: '3.8'

services:

  app:
    image: *BASE_IMAGE*/app:${VERSION}

    networks:
      - app

    secrets:
      - source: laravel_env
        target: /var/www/html/.env

networks:
  app:

secrets:
  laravel_env:
    external: true
