version: '3.8'

services:
  pma:
    depends_on:
      - maria

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.routers.laravel-pma-http.rule=Host(`pma.localhost`)
        - traefik.http.routers.laravel-pma-http.entrypoints=http
        - traefik.http.services.laravel-pma-http.loadbalancer.server.port=80

    image: phpmyadmin:latest

    networks:
      - maria
      - traefik

networks:
  maria:
  traefik:
    external: true
