version: '3.8'

services:

  schedule:
    secrets:
      - source: laravel_env
        target: /var/www/html/.env

    image: *BASE_IMAGE*/schedule:${VERSION}

secrets:
  laravel_env:
    external: true
